services:
    frontend-dev:
        container_name: frontend-dev
        build:
            context: .
            # only builds upto development stage
            target: development
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '3050:3050'
        environment:
            - NODE_ENV=development
        env_file:
            - path: .env
              required: true
