export { ReactComponent as Search } from './searchIcon.svg'
export { ReactComponent as Close } from './closeIcon.svg'
export { ReactComponent as Attempted } from './attemptedIcon.svg'
export { ReactComponent as Todo } from './todoIcon.svg'
export { ReactComponent as Tick } from './tickIcon.svg'
export { ReactComponent as Logout } from './logoutIcon.svg'
export { ReactComponent as Profile } from './profileIcon.svg'
