#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm and use the correct Node version
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm use 22

# Now run lint-staged with the correct Node version
npx lint-staged